language: php

matrix:
  include:
    - php: 5.3.3
      env: DB=mysqli
    - php: 5.3
      env: DB=mysqli # MyISAM
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTNAME="board3/portal"
    - SNIFF="1"        # Should we run code sniffer on your code?
    - IMAGE_ICC="1"    # Should we run icc profile sniffer on your images?
    - COVERALLS="1"    # Should we run coveralls?
    - PHPBB_BRANCH="develop-ascraeus"

branches:
  except:
    - master
    - develop-1_0_X

install:
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cp .coveralls.yml ../../phpBB3/phpBB/.coveralls.yml
  - cd ../../phpBB3
  - sh -c "if [ '$COVERALLS' != '0' ]; then ../board3/Board3-Portal/travis/prepare-coveralls.sh $DB $TRAVIS_PHP_VERSION; fi"
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
  - sh -c "if [ '$COVERALLS' != '0' ]; then ../board3/Board3-Portal/travis/prepare-coverage.sh $DB $TRAVIS_PHP_VERSION; fi"

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION
  - mkdir build/logs
  - chmod +wx build/logs

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/phing-sniff.sh $DB $TRAVIS_PHP_VERSION; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - ../board3/Board3-Portal/travis/run-testsuite.sh $DB $TRAVIS_PHP_VERSION

after_script:
  - php phpBB/vendor/bin/coveralls -v

notifications:
  email:
    recipients:
      - admin@m-a-styles.de
    on_success: change
    on_failure: change
