language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

branches:
  except:
    - master
    - develop-1_0_X

before_script:
  # checkout phpBB and move your extension in place
  - cd ../../
  - git clone "git://github.com/phpbb/phpbb3.git" "phpBB3"
  - mkdir phpBB3/phpBB/ext/board3
  - find -type d -name "Board3-Portal" -print | xargs -i mv {} phpBB3/phpBB/ext/board3/portal

  # Setup the dependencies
  - cd phpBB3/phpBB
  - php ../composer.phar install --dev --no-interaction --prefer-source

  # Setup the tests/travis
  - cd ext/board3/portal
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS phpbb_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database phpbb_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mariadb' ]; then travis/setup-mariadb.sh; fi"
  - sh -c "if [ '$DB' = 'mysql' -o '$DB' = 'mariadb' ]; then mysql -e 'create database IF NOT EXISTS phpbb_tests;'; fi"
  - travis/install-php-extensions.sh
  - phpenv rehash
  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then travis/setup-webserver.sh; fi"
  - rm -R -f phpredis

script:
  - cd ../../../../build
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'mysql' ]; then ../phpBB/vendor/bin/phing sniff; fi"
  - cd ../phpBB/ext/board3/portal
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'mysql' ]; then php develop/spellchecker.php; fi"
  - ../../../vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml

matrix:
  include:
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres

notifications:
  email:
    recipients:
      - admin@m-a-styles.de
    on_success: change
    on_failure: change
