imports:
    - { resource: modules.yml }

parameters:
    board3.version_data:
        author: Marc
        title: Board3 Portal
        tag: board3_portal_v2_dev
        version: board3_portal_version
        file:
            - board3.de
            - updatecheck
            - board3_portal.xml
    board3.config.table: %core.table_prefix%portal_config
    board3.modules.table: %core.table_prefix%portal_modules

services:
    board3.portal.main:
        class: board3\portal\controller\main
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @path_helper
            - %core.root_path%
            - .%core.php_ext%
            - @board3.module_collection
            - %board3.config.table%
            - %board3.modules.table%

    board3.version.check:
        class: board3\portal\includes\mod_version_check
        arguments:
            - %board3.version_data%
            - @config
            - %core.root_path%
            - %core.php_ext%
            - @template
            - @user

    board3.module_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: board3.module }
