parameters:
    board3.version_data:
        author: Marc
        title: Board3 Portal
        tag: board3_portal_v2_dev
        version: board3_portal_version
        file:
            - board3.de
            - updatecheck
            - board3_portal.xml

services:

    board3.portal.main:
        class: \board3\portal\controller\main
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @path_helper
            - %core.root_path%
            - .%core.php_ext%
            - @board3.module_collection

    board3.version.check:
        class: \board3\portal\includes\mod_version_check
        arguments:
            - %board3.version_data%
            - @config
            - %core.root_path%
            - %core.php_ext%
            - @template
            - @user

    board3.module_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: board3.module }

    board3.module.stylechanger:
        class: \board3\portal\modules\stylechanger
        arguments:
            - @config
            - @template
            - @dbal.conn
            - %core.php_ext%
            - %core.root_path%
            - @user
        tags:
            - { name: board3.module }

    board3.module.clock:
        class: \board3\portal\modules\clock
        tags:
            - { name: board3.module }

    board3.module.donation:
        class: \board3\portal\modules\donation
        arguments:
            - @config
            - @template
            - @user
        tags:
            - { name: board3.module }
