imports:
    - { resource: modules.yml }

parameters:
    board3.version_data:
        author: Marc
        title: Board3 Portal
        tag: board3_portal_v2_dev
        version: board3_portal_version
        file:
            - board3.de
            - updatecheck
            - board3_portal.xml
    board3.config.table: %core.table_prefix%portal_config
    board3.modules.table: %core.table_prefix%portal_modules

services:
    board3.portal.main:
        class: board3\portal\controller\main
        arguments:
            - @config
            - @board3.portal.controller_helper
            - @template
            - @user
            - @path_helper
            - %core.root_path%
            - .%core.php_ext%
            - %board3.config.table%
            - %board3.modules.table%

    board3.portal.controller_helper:
        class: board3\portal\controller\helper
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @path_helper
            - @board3.portal.helper
            - %core.root_path%
            - .%core.php_ext%

    board3.version.check:
        class: board3\portal\includes\version_check
        arguments:
            - %board3.version_data%
            - @config
            - %core.root_path%
            - %core.php_ext%
            - @template
            - @user

    board3.module_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: board3.module }

    board3.portal.helper:
        class: board3\portal\includes\helper
        arguments:
            - @board3.module_collection

    board3.portal.modules_helper:
        class: board3\portal\includes\modules_helper
        arguments:
            - @auth
            - @config
            - @request

    board3.portal.fetch_posts:
        class: board3\portal\portal\fetch_posts
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @board3.portal.modules_helper
            - @user

    board3.portal.listener:
        class: board3\portal\event\listener
        arguments:
            - @controller.helper
            - @path_helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
